import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/SideBar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body cz-shortcut-listen="true" className={`antialiased w-full h-screen flex`}>
                <SideBar />
                <main className="flex-1 h-full w-full overflow-auto">
                    <header className="header">
                        <p className="font-bold cursor-pointer">DataStore</p>
                    </header>
                    <div>{children}</div>
                </main>
            </body>
        </html>
    );
}
